# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Zenith' do
    #Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zenith

#pod 'FBSDKCoreKit'
pod 'FBSDKCoreKit' , '~> 4.18.0'
pod 'FBSDKLoginKit' , '~> 4.18.0'
pod 'FBSDKShareKit' , '~> 4.18.0'
pod 'PayPal-iOS-SDK'
pod 'EstimoteSDK'
pod 'Braintree'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'

end
